name: Deploy React App to S3

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'  # Adjust path to your React app directory
      - '.github/workflows/deploy-react.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'  # Adjust path

      - name: Install dependencies
        working-directory: ./frontend  # Adjust path to your React app
        run: npm ci

      - name: Build React app
        working-directory: ./frontend  # Adjust path to your React app
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Adjust to your region

      - name: Sync to S3
        working-directory: ./frontend  # Adjust path
        run: |
          aws s3 sync dist/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deploy status
        run: echo "✅ React app deployed successfully to S3 and CloudFront cache invalidated"